package com.ideacome.mock.mapper;

import com.ideacome.mock.model.ChannelPushConfig;
import com.ideacome.mock.model.ChannelPushConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ChannelPushConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    long countByExample(ChannelPushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    int deleteByExample(ChannelPushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    int insert(ChannelPushConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    int insertSelective(ChannelPushConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    List<ChannelPushConfig> selectByExample(ChannelPushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    ChannelPushConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    int updateByExampleSelective(@Param("record") ChannelPushConfig record, @Param("example") ChannelPushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    int updateByExample(@Param("record") ChannelPushConfig record, @Param("example") ChannelPushConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    int updateByPrimaryKeySelective(ChannelPushConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel_push_config
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    int updateByPrimaryKey(ChannelPushConfig record);
}