package com.ideacome.mock.model;

public class ChannelPushConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_push_config.id
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_push_config.channel_no
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    private String channelNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_push_config.if_auto_insurance
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    private Integer ifAutoInsurance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_push_config.open
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    private Integer open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_push_config.url
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_push_config.channel_param
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    private String channelParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column channel_push_config.tag
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    private String tag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_push_config.id
     *
     * @return the value of channel_push_config.id
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_push_config.id
     *
     * @param id the value for channel_push_config.id
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_push_config.channel_no
     *
     * @return the value of channel_push_config.channel_no
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public String getChannelNo() {
        return channelNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_push_config.channel_no
     *
     * @param channelNo the value for channel_push_config.channel_no
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public void setChannelNo(String channelNo) {
        this.channelNo = channelNo == null ? null : channelNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_push_config.if_auto_insurance
     *
     * @return the value of channel_push_config.if_auto_insurance
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public Integer getIfAutoInsurance() {
        return ifAutoInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_push_config.if_auto_insurance
     *
     * @param ifAutoInsurance the value for channel_push_config.if_auto_insurance
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public void setIfAutoInsurance(Integer ifAutoInsurance) {
        this.ifAutoInsurance = ifAutoInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_push_config.open
     *
     * @return the value of channel_push_config.open
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_push_config.open
     *
     * @param open the value for channel_push_config.open
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_push_config.url
     *
     * @return the value of channel_push_config.url
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_push_config.url
     *
     * @param url the value for channel_push_config.url
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_push_config.channel_param
     *
     * @return the value of channel_push_config.channel_param
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public String getChannelParam() {
        return channelParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_push_config.channel_param
     *
     * @param channelParam the value for channel_push_config.channel_param
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public void setChannelParam(String channelParam) {
        this.channelParam = channelParam == null ? null : channelParam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column channel_push_config.tag
     *
     * @return the value of channel_push_config.tag
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column channel_push_config.tag
     *
     * @param tag the value for channel_push_config.tag
     *
     * @mbg.generated Tue May 15 09:00:12 CST 2018
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }
}